### ISSUE TITLE
question about codes

### ISSUE THREAD

**Issue by DZY-cybe** [cv-rits/CoMoGAN#13]
Thanks for your codes！I have one question about restart a training.In the README.md, I seem to be able to use: python train.py --id train_ID --path_data path/to/waymo/training/dir --gpus 0.But when I use the pretrained model, it builds a new version.Is it right？

**Comment by fabvio** [comment]
It shouldn't. Are you trying to finetune a model?

**Comment by DZY-cybe** [comment]
Yes.I also want to restart a stopped training.

**Comment by fabvio** [comment]
I think this is simply due to the pretrained model being in a folder with a different name. If needed, you can bypass Pytorch Lightning checkpointing mechanism and simply load the model with a `load_state_dict` call.
