### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by Chenanism777** [cv-rits/CoMoGAN#15]
When running translate.py to convert the daytime images to night scenes, it says segmentation failed(core dumped). The size of dataset is only about 700.

cuda version 11.4
RAM:376GB
GPU: RTX TITAN
system:ubuntu 18.04

**Comment by fabvio** [comment]
Hello, can you show the complete logs?

**Comment by Chenanism777** [comment]
I guess it is that specific photo's problem. Thank you so much

**Comment by fabvio** [comment]
Ok, closing.
