### ISSUE TITLE
Which waymo open dataset should I download for training purpose.

### ISSUE THREAD

**Issue by Chenanism777** [cv-rits/CoMoGAN#16]
I went to their website and download https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_0_0 training_0000.tar and try to run the dump_waymo.py. but it says no such file or directory: 'sunny_sequences.txt'

my file structure is like
./scripts
train
dump_waymo.py
sunny_sequences.txt

**Comment by Chenanism777** [comment]
suggestion: line 28 change the path for sunny_sequence.txt into absolute path. I git clone directly but have no idea why cannot load this txt properly. After i change to absolute path, it works.

**Comment by fabvio** [comment]
For future reference, you can just run dump_waymo.py directly from the scripts directory, rather than the root of the project.
