### ISSUE TITLE
Dump waymo dataset fail.

### ISSUE THREAD

**Issue by sjytker** [cv-rits/CoMoGAN#4]
I download waymo_open_dataset_v_1_2_0_individual_files, which file name look like this : "segment-9145030426583202228_1060_000_1080_000_with_camera_labels.tfrecord".

And dump_waymo.py seems to extract nothing, it seems there isn't any file fits in sunny_sequences.txt. So all files are skip.

How to solve this problem? Can I just comment this sunny_sequences.txt?

**Comment by fabvio** [comment]
You're right. There was a bug, I was comparing the whole filename instead of only the first characters. I fixed this in commit 09f2f0f.
