### ISSUE TITLE
Download Waymo Open Dataset 

### ISSUE THREAD

**Issue by creater-zq** [cv-rits/CoMoGAN#8]
Your work has inspired me a lot. Thank you very much.
I want to download Waymo Open Dataset  for training, but I am not sure which one to download. I hope you can let me know, thank you 
![Snipaste_2021-10-04_23-08-13](https://user-images.githubusercontent.com/59300179/135876301-3e9c23ba-7121-4357-9716-9139eec6b063.png)
!

**Comment by fabvio** [comment]
Things are changed since I downloaded the dataset for the research, but I advise you to download the latest version of the perception dataset, so either 3 or 4.

**Comment by creater-zq** [comment]
thanks,i try


| |
张取
|
|
***@***.***
|
签名由网易邮箱大师定制
On 10/4/2021 23:44，Fabio ***@***.***> wrote：

Things are changed since I downloaded the dataset for the research, but I advise you to download the latest version of the perception dataset, so either 3 or 4.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fabvio** [comment]
Ok, closing. Feel free to reopen if you still have problems.
